%YAML:1.0
qtdInput : 2
input00 : avi/in00.avi
input01 : avi/in01.avi
f0: 835.1084859189979
f1: 840.6286190371578
f2: 839.7957543125267
f3: 856.2034875162501

baseline: 18.0

qtdObjects: 3
objNames:
   - "center#0"
   - "center#1"
   - "center#2"

objs:
   -
      name: "center#0"
      markerid: 3
      color: [255, 0, 0]
      qtdConnections: 1
      connections:
         - "center#1"
   -
      name: "center#1"
      markerid: 4
      color: [0, 255, 0]
      qtdConnections: 2
      connections:
         - "center#0"
         - "center#2"
   -
      name: "center#2"
      markerid: 5
      color: [0, 0, 255]
      qtdConnections: 1
      connections:
         - "center#1"
